version: 2

multi-ecosystem-groups:
  monthly-dependencies:
    schedule:
      interval: "monthly"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "monthly-dependencies"
    rebase-strategy: "disabled"

  - package-ecosystem: "uv"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "monthly-dependencies"
    rebase-strategy: "disabled"
