blank_issues_enabled: false
contact_links:
  - name: gsp-py Support
    url: https://github.com/jacksonpradolima/gsp-py
    about: |
      Please only file issues here if they relate to actual bugs or feature requests for the gsp-py project.
      For more general discussions or questions, open an issue and select the appropriate template.
