[package]
name = "gsppy_rust"
version = "0.1.0"
edition = "2021"

[lib]
name = "_gsppy_rust"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.24", features = ["extension-module", "abi3-py310"] }
rayon = "1.10"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
strip = true
